CREATE TABLE dwh_owner.DIM_STORE (
    store_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id VARCHAR2(50) UNIQUE,
    store_name VARCHAR2(200),
    store_type VARCHAR2(50),
    city VARCHAR2(100),
    country VARCHAR2(100),
    region VARCHAR2(100),
    opening_date DATE
);