CREATE TABLE dwh_owner.DIM_SALES_CHANNEL (
    channel_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code VARCHAR2(20) UNIQUE,
    channel_name VARCHAR2(100)
);

INSERT INTO dwh_owner.DIM_SALES_CHANNEL (channel_code, channel_name)
VALUES ('WEB', 'Website');

INSERT INTO dwh_owner.DIM_SALES_CHANNEL (channel_code, channel_name)
VALUES ('MOBILE', 'Mobile App');

INSERT INTO dwh_owner.DIM_SALES_CHANNEL (channel_code, channel_name)
VALUES ('STORE', 'Physical Store');

INSERT INTO dwh_owner.DIM_SALES_CHANNEL (channel_code, channel_name)
VALUES ('PARTNER', 'Partner Marketplace');

COMMIT;