CREATE TABLE dwh_owner.DIM_ORDER_STATUS (
    status_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR2(20) UNIQUE,
    status_description VARCHAR2(200)
);

INSERT INTO dwh_owner.DIM_ORDER_STATUS (status_code, status_description)
VALUES ('PLACED', 'Order placed by customer');

INSERT INTO dwh_owner.DIM_ORDER_STATUS (status_code, status_description)
VALUES ('SHIPPED', 'Order shipped to customer');

INSERT INTO dwh_owner.DIM_ORDER_STATUS (status_code, status_description)
VALUES ('DELIVERED', 'Order delivered successfully');

INSERT INTO dwh_owner.DIM_ORDER_STATUS (status_code, status_description)
VALUES ('CANCELLED', 'Order cancelled before fulfillment');

INSERT INTO dwh_owner.DIM_ORDER_STATUS (status_code, status_description)
VALUES ('RETURNED', 'Order returned by customer');

COMMIT;