CREATE TABLE dwh_owner.DIM_CUSTOMER (
    customer_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR2(50),
    first_name VARCHAR2(100),
    last_name VARCHAR2(100),
    email VARCHAR2(200),
    phone VARCHAR2(50),
    city VARCHAR2(100),
    country VARCHAR2(100),
    customer_segment VARCHAR2(50),
    registration_date DATE,
    effective_from DATE,
    effective_to DATE,
    is_current NUMBER(1),
    record_hash VARCHAR2(64)
);