CREATE TABLE dwh_owner.DIM_PRODUCT (
    product_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR2(50),
    product_name VARCHAR2(200),
    category VARCHAR2(100),
    subcategory VARCHAR2(100),
    brand VARCHAR2(100),
    supplier_id VARCHAR2(50),
    unit_cost NUMBER(12,2),
    list_price NUMBER(12,2),
    effective_from DATE,
    effective_to DATE,
    is_current NUMBER(1),
    record_hash VARCHAR2(64)
);