ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER raw_owner IDENTIFIED BY RawPass2026 
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER stg_owner IDENTIFIED BY StgPass2026 
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER dwh_owner IDENTIFIED BY DwhPass2026 
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER mart_owner IDENTIFIED BY MartPass2026 
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER audit_owner IDENTIFIED BY AuditPass2026 
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO raw_owner;
GRANT CONNECT, RESOURCE TO stg_owner;
GRANT CONNECT, RESOURCE TO dwh_owner;
GRANT CONNECT, RESOURCE TO mart_owner;
GRANT CONNECT, RESOURCE TO audit_owner;

GRANT SELECT ANY TABLE TO stg_owner;
GRANT SELECT ANY TABLE TO dwh_owner;
GRANT SELECT ANY TABLE TO mart_owner;