ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE audit_owner.ETL_RUN (
    run_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name VARCHAR2(100),
    batch_id VARCHAR2(50),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR2(20),
    rows_extracted NUMBER,
    rows_loaded NUMBER,
    rows_rejected NUMBER,
    error_message VARCHAR2(4000)
);

CREATE TABLE audit_owner.ETL_STEP_RUN (
    step_run_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id NUMBER,
    step_name VARCHAR2(100),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR2(20),
    rows_processed NUMBER,
    error_message VARCHAR2(4000)
);

CREATE TABLE audit_owner.REJECTED_RECORDS (
    reject_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR2(50),
    source_table VARCHAR2(100),
    record_key VARCHAR2(200),
    rejection_reason VARCHAR2(1000),
    record_payload CLOB,
    rejected_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE audit_owner.DATA_QUALITY_RESULT (
    check_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR2(50),
    table_name VARCHAR2(100),
    rule_name VARCHAR2(200),
    records_checked NUMBER,
    records_failed NUMBER,
    failure_percentage NUMBER,
    status VARCHAR2(20),
    checked_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE audit_owner.ETL_WATERMARK (
    pipeline_name VARCHAR2(100),
    source_name VARCHAR2(100),
    last_successful_timestamp TIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_watermark PRIMARY KEY (pipeline_name, source_name)
);