-- Step 1: rename existing table
ALTER TABLE dwh_owner.FACT_SALES RENAME TO FACT_SALES_OLD;

-- Step 2: create partitioned version
CREATE TABLE dwh_owner.FACT_SALES (
    sales_key NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id VARCHAR2(50),
    order_item_id VARCHAR2(50),
    date_key NUMBER,
    customer_key NUMBER,
    product_key NUMBER,
    store_key NUMBER,
    channel_key NUMBER,
    status_key NUMBER,
    quantity NUMBER(10),
    unit_price NUMBER(12,2),
    gross_amount NUMBER(14,2),
    discount_amount NUMBER(12,2),
    tax_amount NUMBER(12,2),
    net_amount NUMBER(14,2),
    cost_amount NUMBER(14,2),
    profit_amount NUMBER(14,2),
    batch_id VARCHAR2(50),
    loaded_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_fact_sales PRIMARY KEY (sales_key, date_key),
    CONSTRAINT uq_fact_sales_item UNIQUE (order_item_id, date_key)
)
PARTITION BY RANGE (date_key) (
    PARTITION p_2023 VALUES LESS THAN (20240101),
    PARTITION p_2024 VALUES LESS THAN (20250101),
    PARTITION p_2025 VALUES LESS THAN (20260101),
    PARTITION p_2026 VALUES LESS THAN (20270101),
    PARTITION p_2027 VALUES LESS THAN (20280101),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);

-- Step 3: copy data back
INSERT INTO dwh_owner.FACT_SALES (
    sales_key,
    order_id,
    order_item_id,
    date_key,
    customer_key,
    product_key,
    store_key,
    channel_key,
    status_key,
    quantity,
    unit_price,
    gross_amount,
    discount_amount,
    tax_amount,
    net_amount,
    cost_amount,
    profit_amount,
    batch_id,
    loaded_at
)
SELECT
    sales_key,
    order_id,
    order_item_id,
    date_key,
    customer_key,
    product_key,
    store_key,
    channel_key,
    status_key,
    quantity,
    unit_price,
    gross_amount,
    discount_amount,
    tax_amount,
    net_amount,
    cost_amount,
    profit_amount,
    batch_id,
    loaded_at
FROM dwh_owner.FACT_SALES_OLD;

COMMIT;

-- Step 4: drop old table
DROP TABLE dwh_owner.FACT_SALES_OLD PURGE;