CREATE TABLE dwh_owner.FACT_RETURNS (
    return_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id VARCHAR2(50) UNIQUE,
    order_item_id VARCHAR2(50),
    return_date_key NUMBER,
    customer_key NUMBER,
    product_key NUMBER,
    store_key NUMBER,
    return_quantity NUMBER(10),
    refund_amount NUMBER(12,2),
    return_reason VARCHAR2(200),
    batch_id VARCHAR2(50),
    loaded_at TIMESTAMP DEFAULT SYSTIMESTAMP
);