CREATE TABLE dwh_owner.FACT_SALES_TARGET (
    target_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_key NUMBER,
    month_date_key NUMBER,
    sales_target NUMBER(14,2),
    profit_target NUMBER(14,2),
    batch_id VARCHAR2(50),
    loaded_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_target UNIQUE (store_key, month_date_key)
);